POST http://localhost:8080/wsdl/employee HTTP/1.1
Content-Type: text/xml
SoapAction:

<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/"
            xmlns:gre="http://liga.ru/application/domain/soap/employee">

    <x:Header/>
    <x:Body>
        <gre:addEmployeeRequest>
            <gre:employeeDto>
                <gre:firstname>Huli Nado</gre:firstname>
                <gre:lastname>AA</gre:lastname>
                <gre:salary>190000</gre:salary>
                <gre:positionTitle>MANAGER</gre:positionTitle>
                <gre:departmentTitle>CRM</gre:departmentTitle>
            </gre:employeeDto>
        </gre:addEmployeeRequest>
    </x:Body>
</x:Envelope>

###

POST http://localhost:8080/wsdl/employee HTTP/1.1
Content-Type: text/xml
SoapAction:

<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/"
            xmlns:gre="http://liga.ru/application/domain/soap/employee">

<x:Header/>
<x:Body>
    <gre:updateEmployeeRequest>
        <gre:employeeDto>
            <gre:id>1</gre:id>
            <gre:firstname>Dart</gre:firstname>
            <gre:lastname>Veider</gre:lastname>
            <gre:salary>550100</gre:salary>
            <gre:positionTitle>JUNIOR_DEVELOPER</gre:positionTitle>
            <gre:departmentTitle>CRM</gre:departmentTitle>
        </gre:employeeDto>
    </gre:updateEmployeeRequest>
</x:Body>
</x:Envelope>

###
POST http://localhost:8080/wsdl/employee HTTP/1.1
Content-Type: text/xml
SoapAction:

<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/"
            xmlns:gre="http://liga.ru/application/domain/soap/employee">

    <x:Header/>
    <x:Body>
        <gre:deleteEmployeeRequest>
            <gre:employeeId>6</gre:employeeId>
        </gre:deleteEmployeeRequest>
    </x:Body>
</x:Envelope>

###
POST http://localhost:8080/wsdl/employee HTTP/1.1
Content-Type: text/xml
SoapAction:

<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/"
            xmlns:gre="http://liga.ru/application/domain/soap/employee">

    <x:Header/>
    <x:Body>
        <gre:getEmployeeListRequest>
        </gre:getEmployeeListRequest>
    </x:Body>
</x:Envelope>
