POST http://localhost:8080/wsdl/employee HTTP/1.1
Content-Type: text/xml
SoapAction:

<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/"
            xmlns:gre="http://liga.ru/application/domain/soap/employee">

    <x:Header/>
    <x:Body>
        <gre:addEmployeeRequest>
            <gre:employeeDto>
                <gre:firstname>фыввфывфы</gre:firstname>
                <gre:lastname>фыввфывфы</gre:lastname>
                <gre:salary>40000</gre:salary>
                <gre:positionTitle>JUNIOR_DEVELOPER</gre:positionTitle>
                <gre:departmentTitle>CRM</gre:departmentTitle>
            </gre:employeeDto>
        </gre:addEmployeeRequest>
    </x:Body>
</x:Envelope>

###

POST http://localhost:8080/wsdl/employee HTTP/1.1
Content-Type: text/xml
SoapAction:

<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/"
            xmlns:gre="http://liga.ru/application/domain/soap/employee">

<x:Header/>
<x:Body>
    <gre:updateEmployeeRequest>
        <gre:employeeDto>
            <gre:id>1</gre:id>
            <gre:firstname>Игорь</gre:firstname>
            <gre:lastname>Кульгачев</gre:lastname>
            <gre:salary>55000</gre:salary>
            <gre:positionTitle>JUNIOR_DEVELOPER</gre:positionTitle>
            <gre:departmentTitle>CRM</gre:departmentTitle>
        </gre:employeeDto>
    </gre:updateEmployeeRequest>
</x:Body>
</x:Envelope>
