#Logging
logging:
  level:
    root: INFO
    ru.liga.application: DEBUG

#Datasource
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/liga
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/liga
    schemas: employee_management
    user: postgres
    password: postgres

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  kafka:
    bootstrap-servers: 127.0.0.1:29092
    consumer:
      group-id: employee


scheduler:
  one_minute:
    cron: 0/60 * * * * *


operation:
  task:
    topic:
      employee: manager.local.employee.task.execute