#Datasource
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/liga
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/liga
    schemas: employee_management
    user: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#todo слово раздельно пишется))
# done
scheduler:
  one_minute:
    cron: 0/60 * * * * *