package ru.liga.application.domain.type;

public enum Message {
    POSITION_NOT_FOUND,
    SALARY_NOT_IN_POSITION_RANGE,
    EMPTY_FIRSTNAME,
    EMPTY_LASTNAME,
    EMPTY_POSITION,
    EMPTY_DEPARTMENT,
    EMPLOYEE_NOT_FOUND,
    EMPTY_TASK_DESCRIPTION,
    EMPLOYEES_CREATED
}
